#!/usr/bin/env ruby
# encoding: utf-8
# Rename a list of files to consecutive numbers

require 'flag'

def magnitude(n)
  if n.zero?
    return 1
  end
  mag = 0
  nn = n.to_f
  while nn >= 1.0
    nn /= 10.0
    mag += 1
  end
  mag
end

flags = Flags.new do |flag|
  flag.string 'prefix', '',    'Prefix'
  flag.bool   'n',      false, 'Sort by regexing out a number in filename'
  flag.int    'i',      1,     'Beginning index'
  flag.int    'width',  0,     'Width to pad with zeroes to (0 for auto)'
  flag.bool   'h',      false, 'Show help'
end

if ARGV.size == 0 or flags['h']
  puts 'Usage: autonumber [-prefix PREFIX] files...'
  flags.help
  exit 1
end

i = flags['i']

list = ARGV

if flags['width'] > 0
  mag = flags['width']
else
  mag = magnitude ARGV.size
end

if flags['n']
  list.sort_by! { |file| n = file[/\d+/].to_i; puts "#{file} #{n}"; n }
end

prefix = flags['prefix']
list.each do |filename|
  ext = File.extname(filename)
  `mv "#{filename}" "#{prefix}#{i.to_s.rjust(mag, '0')}#{ext}"`
  i += 1
end
