#!/bin/bash
# Encode a screencap from Camtasia to x264 with music
# x264 options can be tweaked as needed

VIDEO=$1
shift
MUSIC="concat:$(ls --color=never *.mp3 | paste -sd '|')"
OUT="$(basename $VIDEO '.avi').mp4"

avconv -i $VIDEO -i $MUSIC \
	-map 0:v -map 1:a \             # identify stream mappings to use
	-filter:v 'setpts=expr=0.333*PTS,scale=w=1920:h=-1' \  # speed up and resize
	-c:v libx264 -r 30 $@ \         # x264 @ 30fps
	-c:a libvo_aacenc -b:a 128 \    # aac @ 128kbps
	-shortest \                     # cut off the audio when the video ends
	-movflags faststart \           # try to optimize for streaming?
	$OUT
